"""empty message

Revision ID: 9bbc223a777e
Revises: 
Create Date: 2021-10-06 01:21:51.967108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbc223a777e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uid', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
